#!/bin/bash
# BuildMitra Expo Web Builder
# Usage: bash frontend/scripts/build-web.sh
# 
# This script:
# 1. Exports Expo web bundle to frontend/dist/
# 2. Re-creates the nested .gitignore that un-ignores dist files
#    (git rules can't un-ignore children if parent is ignored; nested
#    .gitignore wins over parent rules for its scope)
#
# WHY THIS EXISTS: Root /app/.gitignore has generic 'node_modules/' rule
# which matches Expo's asset path 'frontend/dist/assets/node_modules/*'
# (bundled font glyphs). Without this override, 37 of 41 dist files get
# git-ignored and the Emergent deployment pipeline excludes them from
# the container image, causing production to show a "web build missing"
# error at the root URL.
set -e
cd "$(dirname "$0")/.."   # cd to frontend/
echo "→ Cleaning old dist..."
rm -rf dist
echo "→ Running expo export..."
EXPO_PUBLIC_BACKEND_URL="" npx expo export --platform web --output-dir dist
echo "→ Writing nested .gitignore to un-ignore all dist assets..."
cat > dist/.gitignore << 'EOF'
# Un-ignore EVERYTHING inside this dist folder (Expo web build).
# Nested .gitignore rules WIN over parent rules for this scope.
# This file is REQUIRED — do not delete after rebuild.
# Regenerated by scripts/build-web.sh
!*
!**
!.gitignore
EOF
echo "→ Verifying files trackable..."
cd ..
IGNORED=0
TOTAL=0
while read -r f; do
  TOTAL=$((TOTAL+1))
  git check-ignore "$f" > /dev/null 2>&1 && IGNORED=$((IGNORED+1))
done < <(find frontend/dist -type f)
echo "✅ dist ready: $TOTAL files, $IGNORED ignored, $((TOTAL - IGNORED)) trackable"
if [ "$IGNORED" -ne "0" ]; then
  echo "⚠️  WARNING: $IGNORED files still ignored — check root .gitignore"
  exit 1
fi
echo "🎉 Web build complete. Ready to redeploy."
